FullStackTeste.WebAPI/Models/ErrorViewModel.cs
using System;

namespace FullStackTeste.WebAPI.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

FullStackTeste.WebAPI/Controllers/CheckOutController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using FullStackTeste.WebAPI.Models;

namespace FullStackTest.Web.Controllers
{
    public class CheckOutController : Controller
    {
        // GET: CheckOut
        
        public IActionResult Index()
        {
            
            return View();
        }
    }
}

FullStackTeste.WebAPI/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using FullStackTeste.WebAPI.Models;

namespace FullStackTeste.WebAPI.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

FullStackTeste.WebAPI/Controllers/LandingController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using FullStackTeste.WebAPI.Models;

namespace FullStackTest.Web.Controllers
{
    public class LandingController : Controller
    {
        // GET: Landing
        
        public IActionResult Index()
        {
            return View();
        }
    }
}

FullStackTeste.WebAPI/Controllers/OrderConfirmationController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using FullStackTeste.WebAPI.Models;

namespace FullStackTest.Web.Controllers
{
    public class OrderConfirmationController : Controller
    {
        // GET: OrderConfirmation
        
        public IActionResult Index()
        {
            return View();
        }
    }
}

FullStackTeste.WebAPI/Controllers/ValuesController.cs
using FullStackTeste.Models;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

// For more information on enabling Web API for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace FullStackTeste.WebAPI
{
    [Route("api/[controller]")]
    public class ValuesController : Controller
    {
        [HttpPost]
        public void Post([FromBody]Statistics value)
        {
            var estatisticas =  JsonConvert.SerializeObject(value);

            RabbitMQ.Helper.Sender
                .Create("localhost", "statistic")
                .SendMessage(estatisticas);

        }

    }
}

FullStackTeste.WebAPI/Views/CheckOut/Index.cshtml
@{
    ViewBag.Title = "Checkout do Pedido";
    Layout = "~/Views/Shared/_layout.cshtml";
}

<h2>Checkout do Pedido</h2>

FullStackTeste.WebAPI/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home";
    Layout = "~/Views/Shared/_layout.cshtml";
}


<h2>Home</h2>

FullStackTeste.WebAPI/Views/Landing/Index.cshtml
@{
    ViewBag.Title = "Landing";
    Layout = "~/Views/Shared/_layout.cshtml";
}

<h2>Landing</h2>

FullStackTeste.WebAPI/Views/OrderConfirmation/Index.cshtml
@{
    ViewBag.Title = "Confirmação do Pedido";
    Layout = "~/Views/Shared/_layout.cshtml";
}

<h2>Confirmação do Pedido</h2>

FullStackTeste.WebAPI/Views/Shared/_layout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html lang="en">

<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>


    <script src="https://cdnjs.cloudflare.com/ajax/libs/bowser/1.9.3/bowser.min.js"></script>
    <script src="~/js/fs_scripts/Statistics.js" asp-append-version="true"></script>


    <meta name="viewport" content="width=device-width" />
    <title>_layout</title>
</head>
<body>

    <ul class="nav">
        <li class="nav-item">
            <a class="nav-link active" href="@Url.Action("index","home")">Home</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="@Url.Action("index","Landing")">Landing</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="@Url.Action("index", "CheckOut")">Checkout do Pedido</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="@Url.Action("index","OrderConfirmation")">Confirmação do Pedido</a>
        </li>
    </ul>

    <div class="container-fluid">
        @RenderBody()
    </div>

    <script>
        Statistic.Collect();
    </script>
</body>

</html>